services:
  db:
    build:
      context: .
      dockerfile: mariadb.Dockerfile
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootPw
      MYSQL_DATABASE: vook
      MYSQL_USER: user
      MYSQL_PASSWORD: userPw
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    mem_limit: 300m
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 3s
      start_interval: 2s
      interval: 1m
      timeout: 5s
      retries: 3
  db-init:
    image: migrate/migrate:v4.17.1
    volumes:
      - ./sql:/sql
    command:
      - -source=file:///sql
      - -database=mysql://user:userPw@tcp(db:3306)/vook
      - up
    depends_on:
      db:
        condition: service_healthy
  meilisearch:
    image: getmeili/meilisearch:v1.9.0
    volumes:
      - meili_data:/meili_data
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=aSampleMasterKey
    mem_limit: 1000m
    restart: unless-stopped
  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
    mem_limit: 100m
    restart: unless-stopped

volumes:
  db-data: { }
  meili_data: { }
