spring:
  profiles:
    default: local
    group:
      local: local, modulith
      default: default, modulith
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
