spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/vook
    username: user
    password: userPw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        highlight_sql: false
        format_sql: true
server:
  port: 8080
service:
  meilisearch:
    host: http://localhost:7700
    apiKey: aSampleMasterKey
