### 용어집 리스트
GET http://localhost:8080/glossary

> {%
    let devGlossaryUid = response.body.result.filter((item) => item.name === '개발')[0].uid;
    console.log(devGlossaryUid);
    client.global.set('uid', devGlossaryUid);
%}

### 용어집 내 용어 리스트
GET http://localhost:8080/glossary/{{uid}}/terms
